Major adjustments
* Uses make for compiling Java and Kotlin
* Moved command logic of edit, clear (former clean) and clip (former copy) to bin/base
* Added bin/err for scripts to be sourced when exiting with a given error code
* Modified C and C++ Makefile to support GNU Make 4.1
* Other fixes and adjustments

diff --git a/bin/base/run b/bin/base/run
--- a/bin/base/run
+++ b/bin/base/run
@@ -7,15 +7,17 @@ src="$(bin/call src)"
 
 # If call fails,
 if [[ $? -ne 0 ]]; then
-	# then exit with error
-	exit $?
+	# then exit
+	ret=$?
+	echo "Internal call to src failed." >&2
+	exit $ret
 fi
 
 # If source code exists,
 if [[ -f "$src" ]] ; then
 	# then make subcall
-	bin/subcall "$file"
+	bin/subcall "$file" "$@"
 else
-	# else exit with error
-	exit 1
+	# else exit
+	source bin/err/1
 fi
