Refactoring

diff --git a/libexec/base/clip b/libexec/base/clip
--- a/libexec/base/clip
+++ b/libexec/base/clip
@@ -5,8 +5,11 @@
 # If on WSL, uses clip.
 # Else, uses xclip.
 
+# Exit on error
+set -e
+
 # Get program path
-path="$(libexec/base/path)"
+path=$(libexec/base/path)
 
 # If source is missing,
 if [[ ! -f "$path" ]]; then
diff --git a/libexec/base/debug b/libexec/base/debug
--- a/libexec/base/debug
+++ b/libexec/base/debug
@@ -2,14 +2,20 @@
 #
 # Summary: Run source code in debug mode
 
+# Exit on error
+set -e
+
 # Make call to path
-path="$(libexec/base/path)"
+path=$(libexec/base/path)
 
 # If source code exists,
 if [[ -f "$path" ]] ; then
 	# then make subcall
 	libexec/subcall debug "$@"
 else
+	# Get language
+	lang=$(libexec/get-lang)
+
 	# else exit
 	source libexec/err/1
 fi
diff --git a/libexec/base/list b/libexec/base/list
--- a/libexec/base/list
+++ b/libexec/base/list
@@ -2,11 +2,14 @@
 #
 # Summary: List all saved projects
 
+# Exit on error
+set -e
+
 # Get language
 lang=$(libexec/get-lang)
 
 # Get language project folder
-langprjfolder="etc/projects/$lang"
+langprjfolder=etc/projects/$lang
 
 # If folder exists, list all subdirectories
 if [[ -d "$langprjfolder" ]]; then
diff --git a/libexec/base/load b/libexec/base/load
--- a/libexec/base/load
+++ b/libexec/base/load
@@ -4,6 +4,9 @@
 #
 # Usage: libexec/base/load <project>
 
+# Exit on error
+set -e
+
 if [[ $# -gt 0 ]]; then
 
 	# Get project name
diff --git a/libexec/base/save b/libexec/base/save
--- a/libexec/base/save
+++ b/libexec/base/save
@@ -4,6 +4,9 @@
 #
 # Usage: libexec/base/save <project>
 
+# Exit on error
+set -e
+
 # Check if <project> is present
 if [[ $# -gt 0 ]]; then
 
