Refactoring and clearall command
* Fixed Makefiles not making the right conditions for updating flags
* Simplified error handling with 'set -e'
* Now prohibits setting an unexistent language and creating a new directory for it
* Added clearall command

diff --git a/libexec/call b/libexec/call
--- a/libexec/call
+++ b/libexec/call
@@ -7,6 +7,9 @@
 # If LANG is present, sets it as the current one
 # FILE must be a valid base file
 
+# Exit on failure
+set -e
+
 # Save file name
 file="$1"
 shift
@@ -20,10 +23,6 @@ fi
 
 # Get current language
 lang=$(libexec/get-lang)
-
-if [[ $? -ne 0 ]]; then
-	exit $?
-fi
 
 # Source base file
 source "libexec/base/$file"
diff --git a/libexec/err/3 b/libexec/err/3
--- a/libexec/err/3
+++ b/libexec/err/3
@@ -1,3 +1,3 @@
 #!/usr/bin/env bash
-echo "Error: Missing internal file." >& 2
+echo "Error: Missing internal file." >&2
 exit 3
diff --git a/libexec/subcall b/libexec/subcall
--- a/libexec/subcall
+++ b/libexec/subcall
@@ -6,18 +6,15 @@
 #
 # Calls FILE for the current language
 
+# Exit on failure
+set -e
+
 # Save subfile name
 file="$1"
 shift
 
 # Get current language
 lang="$(libexec/get-lang)"
-
-# If error occurred,
-if [[ $? -ne 0 ]]; then
-	# then exit
-	exit $?
-fi
 
 # Save language directory
 langdir="lib/$lang"
@@ -31,14 +28,8 @@ if [[ -f "$langdir/$file" ]]; then
 	# then run it and pass any additional options
 	"./$file" "$@"
 
-	# Save error code
-	ret=$?
-
 	# Pop directory
 	popd > /dev/null
-
-	# Exit with error code
-	exit $ret
 else
 	# else ask the user if it wants to create it
 	echo "Language '$lang' doesn't have file '$file'." >&2
