bin command

diff --git a/libexec/err/1 b/libexec/err/1
--- a/libexec/err/1
+++ b/libexec/err/1
@@ -1,3 +1,3 @@
 #!/usr/bin/env bash
-echo "Source code is missing." >&2
+echo "Error: Source code is missing." >&2
 exit 1
diff --git a/libexec/err/2 b/libexec/err/2
--- a/libexec/err/2
+++ b/libexec/err/2
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-echo "No language is set." >&2
+echo "Error: No language is set." >&2
 echo "Run ./list to list all available languages." >&2
 echo "Run ./src LANG to set LANG as the current language." >&2
 exit 2
