Refactoring
* rund -> debug
* bin -> xpath
* src -> path
* prjlist -> list
* cplat -> cpt
* Removed cat
* Removed help command

diff --git a/libexec/err/1 b/libexec/err/1
--- a/libexec/err/1
+++ b/libexec/err/1
@@ -1,3 +1,4 @@
 #!/usr/bin/env bash
-echo "Error: Source code for language '$lang' is missing." >&2
+echo "Error: No program for language '$lang' has been writen yet." >&2
+echo "Hint: Run '$programname edit $lang' to write one." >&2
 exit 1
diff --git a/libexec/err/3 b/libexec/err/3
--- a/libexec/err/3
+++ b/libexec/err/3
@@ -1,3 +1,3 @@
 #!/usr/bin/env bash
-echo "Error: Missing internal file '$file' for language '$lang'." >&2
+echo "Error: Language '$lang' doesn't support command '$file'." >&2
 exit 3
diff --git a/libexec/err/5 b/libexec/err/5
--- a/libexec/err/5
+++ b/libexec/err/5
@@ -1,4 +1,4 @@
 #!/usr/bin/env bash
-echo "Error: Unknown $lang project '$prj'." >&2
-echo "Run './prjlist $lang' to list all saved $lang projects." >&2
+echo "Error: Unknown project '$prj' for language '$lang'." >&2
+echo "Hint: Run '$programname list $lang' to list all." >&2
 exit 5
